service: wordle-helper
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'

# TODO: setup custom domain name
# plugins:
#   - serverless-domain-manager

# custom:
#   customDomain:
#     domainName: wordle.j16s.com
#     basePath: ''
#     stage: ${self:provider.stage}
#     createRoute53Record: false

functions:
  api:
    handler: server.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-offline
